authentication/urls.py
from django.urls import include, path
from authentication import views
app_name = 'authentication'

urlpatterns = [
	path('', views.Profile.as_view(), name='profile'),
	path('change_password/', views.change_password_view, name='change_password'),
]

company/urls.py
from django.urls import include, path
from company import views

app_name='company'

urlpatterns = [
    path('', views.GetFilesView.as_view(), name='get_files'),
    path('chart/', views.GoogleChartView.as_view(), name='chart'),
]

gantt/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth import views as auth_views
from authentication import views
from googleoauth.views import OAuth2CallbackView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('projects/', include('projects.urls')),
    path('googleoauth/', include('googleoauth.urls')),
    path('company/', include('company.urls')),
    path('oauthredirect/',OAuth2CallbackView.as_view()),

    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
]

projects/urls.py
from django.urls import include, path
from projects import views, googledrive_view

app_name='projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('add/', views.ProjectCreateView.as_view(), name='project_add'),
    path('gantt/', views.ProjectGanttView.as_view(), name='project_gantt'),
 	path('sheets/', googledrive_view.GoogleSheetView.as_view(), name='google_sheets'),
       
]

gantt/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/eb07455b20.js" crossorigin="anonymous"></script>
    <!-- Custom styles for this template -->  
    <title>Simple Gantt</title>
    {% block css %}
    {% endblock %}
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="d-none d-sm-block my-0 mr-md-auto font-weight-normal">Gantt Chart</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'home' %}"><strong>Home</strong></a>
        {% if user.is_authenticated %}
          <a class="p-2 text-dark" href="{% url 'authentication:profile' %}"><strong>{{ user.username }}</strong></a>
          <a class="p-2 text-danger" href="{% url 'logout' %}"><strong>Sign out</strong></a>
        {% else %}
          <a class="p-2 text-dark" href="{% url 'login' %}">Log in</a>
        {% endif %}        
      </nav>
    </div>
    <div class="container">
    {% block body %}
      
      <div class="card">
        <div class="card-header">
          {% if user.is_authenticated %}
          {% include 'nav.html' %}
          {% endif %}
        </div>
        <div class="card-body" style="min-height: 500px;">          
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
            </div>
          {% endfor %}

          {% block content %}
          {% endblock %}
        </div>
      </div>
      

    {% endblock %}
    </div>

    <!-- JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

gantt/templates/nav.html
{% url 'projects:project_list' as project %}

{% url 'company:get_files' as files %}

<ul class="nav nav-tabs card-header-tabs">
<!-- <li class="nav-item">
  <a class="nav-link{% if project in request.path %} active{% endif %}" href="{{ project }}">Projects </a>
</li> 
<li class="nav-item">
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Processes</a>
</li>
<li class="nav-item">
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Tasks</a>
</li>
<li class="nav-item">
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Sub Tasks</a>
</li> -->

<li class="nav-item">
  <a class="nav-link{% if files in request.path %} active{% endif %}" href="{{ files }}"> Folders</a>
</li>
<li class="nav-item">
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Milestone/Process</a>
</li>
<li class="nav-item">
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Tasks</a>
</li>
</ul>