company/urls.py
from django.urls import include, path
from company import views

app_name='company'

urlpatterns = [
    path('', views.GetFilesView.as_view(), name='get_files'),
    path('chart/', views.GoogleChartView.as_view(), name='chart'),
]

gantt/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth import views as auth_views
from authentication import views
from googleoauth.views import OAuth2CallbackView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('projects/', include('projects.urls')),
    path('googleoauth/', include('googleoauth.urls')),
    path('company/', include('company.urls')),
    path('oauthredirect/',OAuth2CallbackView.as_view()),

    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
]

googleoauth/urls.py
from django.urls import include, path
from googleoauth import views

app_name='googleoauth'

urlpatterns = [
    path('credential_list', views.CredentialsListView.as_view(), name='credential_list'),    
    # path('credential_update/<int:pk>/', views.CredentialsUpdateView.as_view(), name='credential_update'),
    path('credential_add/', views.CredentialsCreateView.as_view(), name='credential_add'),
    path('login/', views.GoogleAuthView.as_view(), name='login'),

]

googleoauth/models.py
from django.db import models
import json 
from django.conf import settings

# Create your models here.
class GoogleOAuth(models.Model):
    """Only 1 item is active at a time"""
    name = models.CharField(max_length=200, default='Test Credentials')
    # you can get this file from https://console.developers.google.com
    # put files in googleoauth/client_secret_json/ folder
    client_secret_filename = models.CharField(max_length=200, default='client_secret_1.json') 
    redirect_uri = models.CharField(max_length=200, default='')
    # ["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/drive.file"]
    scopes = models.TextField(default = '["https://www.googleapis.com/auth/spreadsheets.readonly","https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/drive.file"]')    
    client_id = models.TextField()
    client_secret =  models.TextField()
    status = models.BooleanField(default=True)
    
    def get_scopes(self):
        return json.loads(self.scopes)


class OAuthUsers(models.Model):
    name = models.CharField(max_length=200, default='Test Credentials')
    token = models.TextField(blank=True)
    refresh_token =  models.TextField(blank=True)
    token_uri =  models.TextField(blank=True)
    client_id = models.TextField()
    client_secret =  models.TextField()
    scopes = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    
    def get_scopes(self):
        return json.loads(self.scopes)

    def get_credentials_dict(self):
        return {
            'token': self.token,
            'refresh_token': self.refresh_token,
            'token_uri': self.token_uri,
            'client_id': self.client_id,
            'client_secret': self.client_secret,
            'scopes': self.get_scopes()
        }

    def __str__(self):
        return f'{self.name}({self.status})'

googleoauth/views.py
import os, json
import google_auth_oauthlib.flow

from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib import messages
from django.views import View
from django.http import HttpResponse, JsonResponse

from googleoauth.models import GoogleOAuth, OAuthUsers


class CredentialsListView(LoginRequiredMixin, ListView):
    model = GoogleOAuth

class CredentialsCreateView(LoginRequiredMixin, CreateView):
    model = GoogleOAuth
    fields = ['name','client_secret_filename','redirect_uri','scopes','client_id','client_secret']

    def form_valid(self, form):
        GoogleOAuth.objects.all().update(status=False)
        form.save()
        messages.success(self.request, 'The credentials was created with success!')
        return redirect('googleoauth:credential_list')

class GoogleAuthView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        cred = GoogleOAuth.objects.filter(status=True).first()
        if not cred:
            return HttpResponse('no credentials found')

        # you can get this file from https://console.developers.google.com
        CLIENT_SECRETS_FILE = os.path.join(settings.BASE_DIR,'googleoauth','client_secret_json',cred.client_secret_filename)

        flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
            CLIENT_SECRETS_FILE, scopes=cred.get_scopes())

        flow.redirect_uri = cred.redirect_uri
        authorization_url, state = flow.authorization_url(
            access_type='offline',
            include_granted_scopes='true'
        )

        # Store the state so the callback can verify the auth server response.
        request.session['state'] = state
        return redirect(authorization_url)

#https://developers.google.com/identity/protocols/oauth2/web-server#python_1
class OAuth2CallbackView(View):

    def get(self, request, *args, **kwargs):
        # Specify the state when creating the flow in the callback so that it can
        # verified in the authorization server response.
        cred = GoogleOAuth.objects.filter(status=True).first()
        CLIENT_SECRETS_FILE = os.path.join(settings.BASE_DIR,'googleoauth','client_secret_json',cred.client_secret_filename)


        flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
          CLIENT_SECRETS_FILE, scopes=cred.get_scopes(), state = request.session['state'])
        flow.redirect_uri = cred.redirect_uri

        # Use the authorization server's response to fetch the OAuth 2.0 tokens.
        authorization_response = request.build_absolute_uri() # request.get_full_path()
        flow.fetch_token(authorization_response=authorization_response)

        # Store credentials in the session.
        # ACTION ITEM: In a production app, you likely want to save these
        #              credentials in a persistent database instead.
        credentials = flow.credentials
        if credentials:
            # deactivate all oauthusers
            OAuthUsers.objects.all().update(status=False)
            OAuthUsers.objects.create(
                owner = request.user,
                token =credentials.token,
                refresh_token = credentials.refresh_token or '',
                token_uri= credentials.token_uri,
                client_id= credentials.client_id,
                client_secret= credentials.client_secret,
                scopes= json.dumps(credentials.scopes),
                status = True)
        return redirect('company:get_files')

googleoauth/templates/googleoauth/googlechart.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
<!-- <link rel="stylesheet" href="https://selectize.github.io/selectize.js/css/selectize.default.css" data-theme="default"> -->
    {% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'googleoauth:get_files' %}">Files</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{request.GET.sheet_name}}</li>
    </ol>
  </nav>
  <div class="card"> 
    <div class="card-body"> 
      <form id="#frm_task_edit" method="post" action="{% url 'googleoauth:chart' %}">
        <!-- {% csrf_token %} -->
        <!-- ['id', 'name', 'sdate','edate', 'duration', 'progress','dependencies']-->
        <!-- <input type="hidden" name="sheet_name" value="{{request.GET.sheet_name}}">
        <input type="hidden" name="sheet_id" value="{{request.GET.sheet_id}}"> -->
        <input type="hidden" name="row" id="row">
        <div class="form-row">
          <div class="form-group col-md-1">
            <label for="id">Task ID</label>
            <input type="text" class="form-control" name="id" id="id" onchange="updateTask('id')" readonly="">
          </div>
          <div class="form-group col-md-3">
            <label for="name">Task Name</label>
            <input type="text" class="form-control" name="name" id="name" onchange="updateTask('name')">
          </div>
          <div class="form-group col-md-2">
            <label for="sdate">Start Date</label>
            <input type="date" class="form-control" name="sdate" id="sdate" onchange="updateTask('sdate')">
          </div>
          <div class="form-group col-md-2">
            <label for="edate">End Date</label>
            <input type="date" class="form-control" name="edate" id="edate" onchange="updateTask('edate')">
          </div>
          <div class="form-group col-md-1">
            <label for="duration">Duration</label>
            <input type="number" class="form-control" name="duration" id="duration" onchange="updateTask('duration')">
          </div>
          <div class="form-group col-md-1">
            <label for="progress">Progress%</label>
            <input type="number" class="form-control" name="progress" id="progress" onchange="updateTask('progress')">
          </div>
          <div class="form-group col-md-2">
            <label for="dependencies">Dependencies</label>
            <input type="text" class="form-control" name="dependencies" id="dependencies" onchange="updateTask('dependencies')">
            <!-- <select id="dependencies" name="dependencies[]" multiple onchange="updateTask('dependencies')">
              <option value=""></option>
              {% for item in tasks %}<option value="{{item}}">{{item}}</option>{%endfor %}
            </select> -->
          </div>
          
        </div>
        <div id="ajaxspinner" role="status">
          <span class="sr-only">Saving...</span>
        </div>
        <!-- <button class="btn btn-success btn-sm">Update</button> -->
      </form>
      <div id="chart_div" class="mb-2"></div>
  	</div>
  </div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
<!-- <script src="https://selectize.github.io/selectize.js/js/selectize.js"></script> -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['gantt']});
  google.charts.setOnLoadCallback(onInit);

  // let $select = $('#dependencies').selectize();

  function daysToMilliseconds(days) {
    if (days) {
      // days = Number(days);
      return days * 24 * 60 * 60 * 1000;
    }    
  }

  function convertToDate(item) {
    if (item) return new Date(item);
    return null
  }

  function onInit() {
    $("form").trigger('reset');
    let tasks = {{items|safe}};
    drawChart(tasks)
  }

  function drawChart(tasks) {
    // let tasks = {{items|safe}};
    // tasks = tasks.slice(0,5); // [tasks[0]];
    tasks.forEach((d, i) => { 
      d[2] = convertToDate(d[2]);
      d[3] = convertToDate(d[3]);
      d[4] = daysToMilliseconds(d[4]);
      tasks[i] = d;
    });    

    let data = new google.visualization.DataTable();
    data.addColumn('string', 'Task ID');
    data.addColumn('string', 'Task Name');
    data.addColumn('date', 'Start Date');
    data.addColumn('date', 'End Date');
    data.addColumn('number', 'Duration');
    data.addColumn('number', 'Percent Complete');
    data.addColumn('string', 'Dependencies');

    data.addRows(tasks);

    let options = {
      height: data.getNumberOfRows() * 50,
    };

    let chart = new google.visualization.Gantt(document.getElementById('chart_div'));

    chart.draw(data, options);
    // click event
    google.visualization.events.addListener(chart, 'select', function() {
      if($.isEmptyObject(chart.getSelection())) {  
        // $('form').find("input:not([type='hidden'])").val("");
        $("form").trigger('reset');
        return;
      }
      
      const row = tasks[chart.getSelection()[0].row];
      // alert(tasks[row]);
      $('#row').val(chart.getSelection()[0].row);
      $('#id').val(row[0]);
      $('#name').val(row[1]);
      $('#sdate').val(moment(row[2]).format('YYYY-MM-DD'));
      $('#edate').val(moment(row[3]).format('YYYY-MM-DD'));
      $('#duration').val(row[4]/(24 * 60 * 60 * 1000));
      $('#progress').val(row[5]);
      // if (row[6]) {
      //   let selectize = $select[0].selectize;
      //   selectize.setValue(selectize.search(row[6]).items[0].id);
      //   alert(row[6]);
      // }
      $('#dependencies').val(row[6]);
      
    });
  }
  

  function updateTask(item) {
    // console.log(item);
    $("#ajaxspinner").addClass('spinner-border');
    $.post("{% url 'googleoauth:chart' %}", { sheet_id:"{{request.GET.sheet_id}}",row:$("#row").val(),
      column_name: item, data: $("#"+item).val(), csrfmiddlewaretoken: '{{ csrf_token }}'})
      .done(function(tasks) {
        // alert("Data Loaded: " + data);
        $("#ajaxspinner").removeClass('spinner-border');
        drawChart(tasks);
      });
  }
</script>
{% endblock %}

googleoauth/templates/googleoauth/googleoauth_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'googleoauth:credential_list' %}">Credentials</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new Credentials</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
    </div>
  </div>
{% endblock %}

googleoauth/templates/googleoauth/googleoauth_list.html
{% extends 'base.html' %}

{% block content %}
{# include 'googleoauth/nav.html' #}
<hr>
<h3>Google API Credentials</h3>
<a class="btn btn-sm btn-success mb-3" href="{% url 'googleoauth:credential_add' %}"><i class="fas fa-plus"></i> Add New</a>
<div class="row">
  <div class="col-md-6">
{% for cred in object_list %}
<div class="card{% if cred.status %} border-success{%endif%} mb-3">
  <div class="card-header">
    {{ cred.name }}
  </div>
  <div class="card-body">
    <code>{{ cred.scopes }}</code>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{ cred.client_secret_filename }}</li>
    <li class="list-group-item"><a href="#">{{ cred.redirect_uri }}</a></li>
    <li class="list-group-item">{{ cred.client_id }}</li>
  </ul>
  <div class="card-body">
    <p class="card-text">Client Secret: {{ cred.client_secret }}</p>
  </div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}