company/urls.py
from django.urls import include, path
from company import views

app_name='company'

urlpatterns = [
    path('', views.GetFilesView.as_view(), name='get_files'),
    path('chart/', views.GoogleChartView.as_view(), name='chart'),
]

gantt/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth import views as auth_views
from authentication import views
from googleoauth.views import OAuth2CallbackView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('projects/', include('projects.urls')),
    path('googleoauth/', include('googleoauth.urls')),
    path('company/', include('company.urls')),
    path('oauthredirect/',OAuth2CallbackView.as_view()),

    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
]

googleoauth/urls.py
from django.urls import include, path
from googleoauth import views

app_name='googleoauth'

urlpatterns = [
    path('credential_list', views.CredentialsListView.as_view(), name='credential_list'),    
    # path('credential_update/<int:pk>/', views.CredentialsUpdateView.as_view(), name='credential_update'),
    path('credential_add/', views.CredentialsCreateView.as_view(), name='credential_add'),
    path('login/', views.GoogleAuthView.as_view(), name='login'),

]

company/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=200, unique=True)
    folder_id = models.CharField(max_length=255, blank=True)
    milestone_sheet_id = models.CharField(max_length=255, blank=True)
    task_sheet_id = models.CharField(max_length=255, blank=True)
    def __str__(self):
        return self.name

    def clean(self):
        self.name = self.name.title()

company/views.py
import os, json
import pandas as pd
import numpy as np

import google.oauth2.credentials
import googleapiclient.discovery

from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse, JsonResponse, Http404
from django.contrib.auth.mixins import LoginRequiredMixin

from googleoauth.models import OAuthUsers

def get_credentials(app = 'drive'):
    """
    for drive use:
        drive = get_credentials()
        files = drive.files()
        
    for spreadsheet use:
        sheet = get_credentials('sheets')
        sheet.spreadsheets()
    """
    credentials = OAuthUsers.objects.filter(status=True).first()
    if not credentials:
        # if google account not connected, show google login
        # return JsonResponse({'status':'false','message':'There is no google accounts connected.'}, status=500) #redirect('googleoauth:login')
        raise Http404('There is no active google accounts. Please set a google account active or connect a new account.')
    
    credentials = google.oauth2.credentials.Credentials(**credentials.get_credentials_dict())
    if app=='drive':
        version = 'v3'
    elif app == 'sheets':
        version = 'v4'
    return googleapiclient.discovery.build(app, version, credentials=credentials)

class GetFilesView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        drive = get_credentials()
        # files = drive.files().list().execute()
        files = drive.files().list(q=f"'{request.user.company.folder_id}' in parents",
            spaces='drive',fields='nextPageToken, files(id, name, mimeType)',pageToken=None).execute()

        return render(request, 'company/files.html',{'files':files})


class GoogleChartView(LoginRequiredMixin, View):
    def date_to_str(self, date):
        try: 
            return date.strftime("%Y-%m-%dT%H:%M:%S%z")
        except:
            return None

    def blank_to_none(self, items):
        new = []
        for sub_items in items:
            row = []
            for item in sub_items:
                row.append(None if item == '' else item)
            new.append(row)
        return new

    def get_spreadsheet_data(self, sheet, sheet_id, sheet_range='!A2:G'):
        result = sheet.values().get(spreadsheetId=sheet_id,range=sheet_range).execute()
        values = result.get('values', [])
        
        columns = ['id', 'name', 'dependencies', 'sdate','edate', 'duration', 'progress']
        df = pd.DataFrame(np.array(values), columns=columns)
        
        df['sdate'] = pd.to_datetime(df['sdate']).apply(lambda x: self.date_to_str(x))
        df['edate'] = pd.to_datetime(df['edate']).apply(lambda x: self.date_to_str(x))
        df['progress'] = df['progress'].str.replace(r'\D', '').astype(int)

        df=df.reindex(columns=['id', 'name', 'sdate','edate', 'duration', 'progress','dependencies'])

        items = df.values.tolist() #list(df.values) #df.values.tolist()

        return self.blank_to_none(items)

    def post(self, request):
        # update cell in google sheet
        # 'row': ['3'], 'column_name': ['progress'], 'data': ['1']
        row = int(request.POST['row'])+2 # skip Heading and make it start from 1
        column= request.POST['column_name']
        data = request.POST['data']
        columns={'id':'A', 'name':'B', 'dependencies':'C','sdate':'D','edate':'E', 'duration':'F', 
            'progress':'G'}

        sheet_range = f'!{columns[column]}{row}'
        body = {
            'values': [[data]]
        }
        sheet = get_credentials('sheets')
        result = sheet.spreadsheets().values().update(
            spreadsheetId=request.POST['sheet_id'], range=sheet_range,
            valueInputOption='RAW', body=body).execute()

        items = self.get_spreadsheet_data(sheet,request.POST['sheet_id'])
        return JsonResponse(items, safe=False)

    def get(self, request):
        sheet = get_credentials('sheets')
        items = self.get_spreadsheet_data(sheet.spreadsheets(),request.GET['sheet_id'])
        # items2 = [["Research","Find sources","2014-12-31T18:30:00.000Z","2015-01-04T18:30:00.000Z",None,100,None],]
        return render(request, 'company/googlechart.html', {'items':json.dumps(items)}) # 'tasks':df.id.tolist()})

company/templates/company/files.html
{% extends 'base.html' %}

{% block content %}
  <div class="card"> 
    <h4>{{user.company.name}}</h4>
  	<table class="table table-bordered mb-0">
      <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for file in files.files %}
        
        <tr>
          <td class="align-middle">{{ file.name }}</td>
          <td>
            {%if file.mimeType == "application/vnd.google-apps.spreadsheet" %}
            <form method="get" action="{% url 'company:chart' %}">
              <input type="hidden" name="sheet_id" value="{{file.id}}">
              <input type="hidden" name="sheet_name" value="{{file.name}}">
              <button type="submit" class="btn btn-sm btn-info">Chart</button>
            </form>
            {% endif %}
          </td>
        </tr>
        
      {% endfor %}
      </tbody>
    </table>    
  </div>
{% endblock %}

company/templates/company/googlechart.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
<!-- <link rel="stylesheet" href="https://selectize.github.io/selectize.js/css/selectize.default.css" data-theme="default"> -->
    {% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'company:get_files' %}">Files</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{request.GET.sheet_name}}</li>
    </ol>
  </nav>
  <div class="card"> 
    <div class="card-body"> 
      <form id="#frm_task_edit" method="post" action="{% url 'company:chart' %}">
        <!-- {% csrf_token %} -->
        <!-- ['id', 'name', 'sdate','edate', 'duration', 'progress','dependencies']-->
        <!-- <input type="hidden" name="sheet_name" value="{{request.GET.sheet_name}}">
        <input type="hidden" name="sheet_id" value="{{request.GET.sheet_id}}"> -->
        <input type="hidden" name="row" id="row">
        <div class="form-row">
          <div class="form-group col-md-1">
            <label for="id">Task ID</label>
            <input type="text" class="form-control" name="id" id="id" onchange="updateTask('id')" readonly="">
          </div>
          <div class="form-group col-md-3">
            <label for="name">Task Name</label>
            <input type="text" class="form-control" name="name" id="name" onchange="updateTask('name')">
          </div>
          <div class="form-group col-md-2">
            <label for="sdate">Start Date</label>
            <input type="date" class="form-control" name="sdate" id="sdate" onchange="updateTask('sdate')">
          </div>
          <div class="form-group col-md-2">
            <label for="edate">End Date</label>
            <input type="date" class="form-control" name="edate" id="edate" onchange="updateTask('edate')">
          </div>
          <div class="form-group col-md-1">
            <label for="duration">Duration</label>
            <input type="number" class="form-control" name="duration" id="duration" onchange="updateTask('duration')">
          </div>
          <div class="form-group col-md-1">
            <label for="progress">Progress%</label>
            <input type="number" class="form-control" name="progress" id="progress" onchange="updateTask('progress')">
          </div>
          <div class="form-group col-md-2">
            <label for="dependencies">Dependencies</label>
            <input type="text" class="form-control" name="dependencies" id="dependencies" onchange="updateTask('dependencies')">
            <!-- <select id="dependencies" name="dependencies[]" multiple onchange="updateTask('dependencies')">
              <option value=""></option>
              {% for item in tasks %}<option value="{{item}}">{{item}}</option>{%endfor %}
            </select> -->
          </div>
          
        </div>
        <div id="ajaxspinner" role="status">
          <span class="sr-only">Saving...</span>
        </div>
        <!-- <button class="btn btn-success btn-sm">Update</button> -->
      </form>
      <div id="chart_div" class="mb-2"></div>
  	</div>
  </div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
<!-- <script src="https://selectize.github.io/selectize.js/js/selectize.js"></script> -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['gantt']});
  google.charts.setOnLoadCallback(onInit);

  // let $select = $('#dependencies').selectize();

  function daysToMilliseconds(days) {
    if (days) {
      // days = Number(days);
      return days * 24 * 60 * 60 * 1000;
    }    
  }

  function convertToDate(item) {
    if (item) return new Date(item);
    return null
  }

  function onInit() {
    $("form").trigger('reset');
    let tasks = {{items|safe}};
    drawChart(tasks)
  }

  function drawChart(tasks) {
    // let tasks = {{items|safe}};
    // tasks = tasks.slice(0,5); // [tasks[0]];
    tasks.forEach((d, i) => { 
      d[2] = convertToDate(d[2]);
      d[3] = convertToDate(d[3]);
      d[4] = daysToMilliseconds(d[4]);
      tasks[i] = d;
    });    

    let data = new google.visualization.DataTable();
    data.addColumn('string', 'Task ID');
    data.addColumn('string', 'Task Name');
    data.addColumn('date', 'Start Date');
    data.addColumn('date', 'End Date');
    data.addColumn('number', 'Duration');
    data.addColumn('number', 'Percent Complete');
    data.addColumn('string', 'Dependencies');

    data.addRows(tasks);

    let options = {
      height: data.getNumberOfRows() * 50,
    };

    let chart = new google.visualization.Gantt(document.getElementById('chart_div'));

    chart.draw(data, options);
    // click event
    google.visualization.events.addListener(chart, 'select', function() {
      if($.isEmptyObject(chart.getSelection())) {  
        // $('form').find("input:not([type='hidden'])").val("");
        $("form").trigger('reset');
        return;
      }
      
      const row = tasks[chart.getSelection()[0].row];
      // alert(tasks[row]);
      $('#row').val(chart.getSelection()[0].row);
      $('#id').val(row[0]);
      $('#name').val(row[1]);
      $('#sdate').val(moment(row[2]).format('YYYY-MM-DD'));
      $('#edate').val(moment(row[3]).format('YYYY-MM-DD'));
      $('#duration').val(row[4]/(24 * 60 * 60 * 1000));
      $('#progress').val(row[5]);
      // if (row[6]) {
      //   let selectize = $select[0].selectize;
      //   selectize.setValue(selectize.search(row[6]).items[0].id);
      //   alert(row[6]);
      // }
      $('#dependencies').val(row[6]);
      
    });
  }
  

  function updateTask(item) {
    // console.log(item);
    $("#ajaxspinner").addClass('spinner-border');
    $.post("{% url 'googleoauth:chart' %}", { sheet_id:"{{request.GET.sheet_id}}",row:$("#row").val(),
      column_name: item, data: $("#"+item).val(), csrfmiddlewaretoken: '{{ csrf_token }}'})
      .done(function(tasks) {
        // alert("Data Loaded: " + data);
        $("#ajaxspinner").removeClass('spinner-border');
        drawChart(tasks);
      });
  }
</script>
{% endblock %}