gantt/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth import views as auth_views
from authentication import views
from googleoauth.views import OAuth2CallbackView

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('projects/', include('projects.urls')),
    path('googleoauth/', include('googleoauth.urls')),
    path('company/', include('company.urls')),
    path('oauthredirect/',OAuth2CallbackView.as_view()),

    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
]

projects/urls.py
from django.urls import include, path
from projects import views, googledrive_view

app_name='projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('add/', views.ProjectCreateView.as_view(), name='project_add'),
    path('gantt/', views.ProjectGanttView.as_view(), name='project_gantt'),
 	path('sheets/', googledrive_view.GoogleSheetView.as_view(), name='google_sheets'),
       
]

projects/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Project(models.Model):    
    project_id = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    start_date= models.DateTimeField()
    end_date = models.DateTimeField()
    progress = models.IntegerField(default=0)
    dependencies = models.CharField(max_length=50, blank=True) # project id dependences
    created_on = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class GoogleDriveAuth(models.Model):
    key =  models.TextField()
    token_id = models.TextField(blank=True)
    access_token = models.TextField()
    refresh_token =  models.TextField()
    client_id = models.TextField()
    client_secret =  models.TextField()
    token_start_time = models.DateTimeField(auto_now_add = True)
    token_expiry_time = models.IntegerField(null=True,blank=True)
    status = models.BooleanField(default=True)

projects/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib import messages
from django.views import View

from projects.models import Project
from authentication.mixins import CreatorRequiredMixin



class ProjectListView(LoginRequiredMixin, ListView):
    model = Project


class ProjectCreateView(CreatorRequiredMixin, CreateView):
    model = Project
    fields = ('project_id', 'name', 'start_date', 'end_date', 'progress','dependencies')
    template_name = 'projects/project_add_form.html'

    def form_valid(self, form):
        project = form.save(commit=False)
        project.owner = self.request.user
        project.save()
        messages.success(self.request, 'The project was created with success!')
        return redirect('projects:project_list')


class ProjectGanttView(LoginRequiredMixin, View):
    template_name = 'projects/graph.html'

    def get(self, request, *args, **kwargs):
        project_list = []

        for project in Project.objects.all():
            proj_dict = {
                'start': str(project.start_date.date()),
                'end': str(project.end_date.date()),
                'name': project.name,
                'id': project.project_id,
                'progress': project.progress
            }
            if project.dependencies:
                proj_dict['dependencies'] = project.dependencies
            project_list.append(proj_dict)

        return render(request, self.template_name, {'projects':project_list})

projects/templates/projects/graph.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'frappe/frappe-gantt.css' %}">
<style type="text/css">
    .gantt .bar-milestone .bar {
            fill: tomato;
        }
        .gantt_container {
            width: 80%;
            margin: 0 auto;
        }
</style>
{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'projects:project_list' %}">Projects</a></li>
      <li class="breadcrumb-item active" aria-current="page">View project</li>
    </ol>
  </nav>

    <div class="mx-auto mt-3 btn-group" role="group">
      <button type="button" class="btn btn-sm btn-light active">Quarter Day</button>
      <button type="button" class="btn btn-sm btn-light">Half Day</button>
      <button type="button" class="btn btn-sm btn-light">Day</button>
      <button type="button" class="btn btn-sm btn-light">Week</button>
      <button type="button" class="btn btn-sm btn-light">Month</button>
    </div>
    <div class="gantt_container" style="overflow: scroll"><svg id="gantt"></svg></div>  
{% endblock %}


{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script src="{% static 'frappe/snap.svg.js' %}"></script>
<script src="{% static 'frappe/frappe-gantt-0.0.7.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    console.log('asdf');
    //"{{ data|safe }}";
    var projects = {{projects|safe}};
    // var tasks = [
    //         {
    //             start: '2018-10-01',
    //             end: '2018-10-08',
    //             name: 'Redesign website',
    //             id: "Task 0",
    //             progress: 20
    //         }]
    var gantt = new Gantt("#gantt", projects, {            
        on_date_change: function(task, start, end) {                
            alert(end);
        },
        on_progress_change: function(task, progress) {
            alert(progress);
        }
    });

    
    $(".btn-group").on("click", "button", function() {
        $btn = $(this);
        var mode = $btn.text();
        gantt.change_view_mode(mode);
        $btn.parent().find('button').removeClass('active');
            $btn.addClass('active');
    });
});
</script>
{% endblock %}

projects/templates/projects/project_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'projects:project_list' %}">Projects</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new project</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new project</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
    </div>
  </div>
{% endblock %}

projects/templates/projects/project_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'datatables/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
  {% if request.user.is_creator %}
    <a class="btn btn-success" href="{% url 'projects:project_add' %}"><i class="fas fa-plus"></i> Add Project</a>
  {% endif %}
  <a href="{% url 'projects:project_gantt' %}" class="btn btn-info"><i class="fas fa-chart-bar"></i> View Chart</a>

  <a href="{% url 'projects:google_sheets' %}" class="btn btn-info"><i class="fas fa-file-excel"></i> </a>
  <hr>
  <div class="card"> 
    <table class="table table-bordered mb-0" id="tb_projectlist">
      <thead>

      <tr>
        <th>Project</th>
        <th class="d-none d-sm-table-cell">Name</th>
        <th class="d-none d-sm-table-cell">Start Date</th>
        <th class="d-none d-sm-table-cell">End Date</th>
        <th class="d-none d-sm-table-cell">Progress</th>
        <th class="d-none d-sm-table-cell">Dependencies</th>
      </tr>
    </thead>
    <tbody>
      {% for project in object_list %}
        <tr{% if project.owner == request.user %} style="background: #fdf7e3"{%endif%}>
          <td class="align-middle">{{ project.project_id }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ project.name }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ project.start_date }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ project.end_date }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ project.progress }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ project.dependencies }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

{% block js %}
<script src="{% static 'datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'datatables/dataTables.bootstrap4.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#tb_projectlist').DataTable({"order": [[ 1, "desc" ]]});
});
</script>
{% endblock %}